### PR TITLE
test(iframe): increase timeouts

### PR DESCRIPTION
**Pull request by opichals**

### CODE REVIEW

**Comment by opichals** [comment]
It is using jasmine https://github.com/apiaryio/console-proxy/blob/master/karma.iframe.conf.js#L24

The docs for that are here: https://jasmine.github.io/api/edge/global.html#it

**Comment by opichals** [comment]
The real issue here is the unpkg.com use for the dependency fetch (only used in the server:3001/apiary/proxy which is AFACS used only for tests:

https://github.com/apiaryio/console-proxy/blob/master/server/serve-seed.ejs

**Comment by opichals** [comment]
So this sounds like just a temporary measure for the tests to fail less likely and should get a proper treatment of packaging the .ejs libraries into a single static file served locally by the server for the tests.

**Comment by JackuB** [comment]
TIL AFACS (as far as I can see?)

**Comment by char0n** [comment]
Agree; sorry did not notice it's jasmine

**Pull request merged**
